# Generated by Django 5.2.8 on 2025-11-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("setting_id", models.AutoField(primary_key=True, serialize=False)),
                ("fuel_type", models.CharField(max_length=50)),
                (
                    "price_per_liter",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=12)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("station_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="service.company",
                    ),
                ),
                (
                    "manager_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_stations",
                        to="service.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pump",
            fields=[
                ("pump_id", models.AutoField(primary_key=True, serialize=False)),
                ("pump_number", models.IntegerField()),
                ("fuel_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("offline", "Offline")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("flow_rate", models.FloatField(blank=True, null=True)),
                (
                    "station_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pumps",
                        to="service.station",
                    ),
                ),
            ],
            options={
                "unique_together": {("station_id", "pump_number")},
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("fuel_type", models.CharField(max_length=50)),
                ("quantity", models.FloatField()),
                ("capacity", models.FloatField()),
                ("min_threshold", models.FloatField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="service.station",
                    ),
                ),
            ],
            options={
                "unique_together": {("station_id", "fuel_type")},
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("alert_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("maintenance", "Maintenance"),
                            ("inventory", "Inventory"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "inventory_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="service.inventory",
                    ),
                ),
                (
                    "pump_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="service.pump",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("fuel_type", models.CharField(max_length=50)),
                ("quantity", models.FloatField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("momo", "Mobile Money"),
                            ("card", "Card"),
                        ],
                        max_length=10,
                    ),
                ),
                ("car_plate", models.CharField(blank=True, max_length=20, null=True)),
                ("transaction_time", models.DateTimeField(auto_now_add=True)),
                (
                    "pump_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="service.pump"
                    ),
                ),
                (
                    "station_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.station",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="service.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="service.user",
            ),
        ),
    ]
