# Generated by Django 5.2.8 on 2025-11-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pump",
            old_name="station_id",
            new_name="station",
        ),
    ]
