# Generated by Django 5.2.8 on 2025-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_rename_station_id_pump_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
