# Generated by Django 5.2.8 on 2025-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pump",
            name="fuel_type",
            field=models.CharField(
                choices=[("petrol", "Petrol (Gasoline)"), ("diesel", "Diesel")],
                default="petrol",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="fuel_type",
            field=models.CharField(
                choices=[("petrol", "Petrol (Gasoline)"), ("diesel", "Diesel")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
