# Generated by Django 5.2.8 on 2025-12-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0004_alter_pump_fuel_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="station_id",
            new_name="station",
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("station", "fuel_type")},
        ),
    ]
