# Generated by Django 5.2.8 on 2025-12-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_alter_systemsetting_fuel_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pump",
            name="fuel_type",
            field=models.CharField(max_length=50),
        ),
    ]
